.TH "C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program Directory Reference" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcity\&.h\fP"
.br
.ti -1c
.RI "file \fBcityselectwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcityselectwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.h\fP"
.br
.ti -1c
.RI "file \fBdbinit\&.h\fP"
.br
.ti -1c
.RI "file \fBeditwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeditwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBfood\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfood\&.h\fP"
.br
.ti -1c
.RI "file \fBfoodselectwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfoodselectwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBloginwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBloginwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBresultswindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBresultswindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_cityselectwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_editwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_foodselectwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_loginwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_mainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_resultswindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_tripwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBui_viewwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBviewwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBviewwindow\&.h\fP"
.br
.in -1c
