.TH "C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/city.h" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/city.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'food\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCityDistance\fP"
.br
.RI "\fBCityDistance\fP struct A struct which contains the distance from a given city to another city\&. "
.ti -1c
.RI "class \fBCity\fP"
.br
.RI "\fBCity\fP class This is the \fBCity\fP class used to instantiate, store, and perform calculations on cities\&. "
.ti -1c
.RI "struct \fBCompareCity\fP"
.br
.RI "\fBCompareCity\fP struct A comparator for cities\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
