.TH "City" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
City \- \fBCity\fP class This is the \fBCity\fP class used to instantiate, store, and perform calculations on cities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <city\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCity\fP ()"
.br
.RI "\fBCity()\fP Default Constructor\&. "
.ti -1c
.RI "\fBCity\fP (QString name, std::vector< \fBCityDistance\fP > otherCities, std::vector< \fBFood\fP > foods, bool isStart=false)"
.br
.RI "\fBCity\fP(QString name, std::vector<CityDistance> otherCities, std::vector<Food> foods, bool isStart = false) Overloaded Constructor\&. "
.ti -1c
.RI "QString \fBgetName\fP ()"
.br
.RI "\fBgetName()\fP This method returns a QString containing the name of the \fBCity\fP "
.ti -1c
.RI "QString \fBgetName\fP () const"
.br
.RI "\fBgetName() const\fP Const method which returns a QString containing the name of the \fBCity\fP "
.ti -1c
.RI "int \fBgetNumFoods\fP ()"
.br
.RI "\fBgetNumFoods()\fP This method returns the number of foods in a \fBCity\fP's food vector "
.ti -1c
.RI "bool \fBgetIsStart\fP () const"
.br
.RI "\fBgetIsStart()\fP Returns the value of the 'isStart' data member If the city is the starting city, return true\&. Else, return false\&. "
.ti -1c
.RI "bool \fBsetIsStart\fP (bool value)"
.br
.RI "\fBsetIsStart()\fP Sets a the value of a \fBCity\fP's isStart data member "
.ti -1c
.RI "std::vector< \fBFood\fP > \fBgetFoods\fP ()"
.br
.RI "\fBgetFoods()\fP Returns the \fBCity\fP's food vector to the client "
.ti -1c
.RI "void \fBremoveCityDistance\fP (QString name)"
.br
.RI "\fBremoveCityDistance()\fP Removes all distances related to the argument city from the \fBCity\fP's distance vector "
.ti -1c
.RI "void \fBsortDistances\fP ()"
.br
.RI "\fBsortDistances()\fP Sorts the \fBCity\fP's distance vector in order of shortest to longest distance "
.ti -1c
.RI "\fBCityDistance\fP \fBgetShortestDistance\fP () const"
.br
.RI "\fBgetShortestDistance()\fP Returns the distance to the closest city in the city vector "
.in -1c
.SH "Detailed Description"
.PP 
\fBCity\fP class This is the \fBCity\fP class used to instantiate, store, and perform calculations on cities\&. 


.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBDate:\fP
.RS 4
October 2019 
.RE
.PP

.PP
Definition at line 59 of file city\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "City::City ()"

.PP
\fBCity()\fP Default Constructor\&. 
.PP
Definition at line 3 of file city\&.cpp\&.
.SS "City::City (QString name, std::vector< \fBCityDistance\fP > otherCities, std::vector< \fBFood\fP > foods, bool isStart = \fCfalse\fP)"

.PP
\fBCity\fP(QString name, std::vector<CityDistance> otherCities, std::vector<Food> foods, bool isStart = false) Overloaded Constructor\&. 
.PP
Definition at line 6 of file city\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBFood\fP > City::getFoods ()"

.PP
\fBgetFoods()\fP Returns the \fBCity\fP's food vector to the client 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<food> 
.RE
.PP

.PP
Definition at line 66 of file city\&.cpp\&.
.SS "bool City::getIsStart () const"

.PP
\fBgetIsStart()\fP Returns the value of the 'isStart' data member If the city is the starting city, return true\&. Else, return false\&. 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 56 of file city\&.cpp\&.
.SS "QString City::getName ()"

.PP
\fBgetName()\fP This method returns a QString containing the name of the \fBCity\fP 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
QString 
.RE
.PP

.PP
Definition at line 10 of file city\&.cpp\&.
.SS "QString City::getName () const"

.PP
\fBgetName() const\fP Const method which returns a QString containing the name of the \fBCity\fP 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
QString 
.RE
.PP

.PP
Definition at line 15 of file city\&.cpp\&.
.SS "int City::getNumFoods ()"

.PP
\fBgetNumFoods()\fP This method returns the number of foods in a \fBCity\fP's food vector 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 51 of file city\&.cpp\&.
.SS "\fBCityDistance\fP City::getShortestDistance () const"

.PP
\fBgetShortestDistance()\fP Returns the distance to the closest city in the city vector 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBCityDistance\fP 
.RE
.PP

.PP
Definition at line 38 of file city\&.cpp\&.
.SS "void City::removeCityDistance (QString name)"

.PP
\fBremoveCityDistance()\fP Removes all distances related to the argument city from the \fBCity\fP's distance vector 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 20 of file city\&.cpp\&.
.SS "bool City::setIsStart (bool value)"

.PP
\fBsetIsStart()\fP Sets a the value of a \fBCity\fP's isStart data member 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP value 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 61 of file city\&.cpp\&.
.SS "void City::sortDistances ()"

.PP
\fBsortDistances()\fP Sorts the \fBCity\fP's distance vector in order of shortest to longest distance 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 32 of file city\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
