.TH "CitySelectWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CitySelectWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cityselectwindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmoveToFoodSelectClicked\fP ()"
.br
.RI "moveToFoodSelectClicked Proceeds to the \fBFood\fP Select window "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCitySelectWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~CitySelectWindow\fP ()"
.br
.ti -1c
.RI "void \fBsetCitySelection\fP ()"
.br
.RI "\fBsetCitySelection()\fP Sets the city selection of the \fBCitySelectWindow\fP "
.ti -1c
.RI "std::vector< \fBCity\fP > & \fBgetLoadedCities\fP ()"
.br
.RI "\fBgetLoadedCities()\fP Returns a vector containing the currently loaded cities "
.ti -1c
.RI "int \fBgetPlanNumber\fP ()"
.br
.RI "\fBgetPlanNumber()\fP Returns the value of the selected trip plan "
.ti -1c
.RI "void \fBsetPlanNumber\fP (int number)"
.br
.RI "\fBsetPlanNumber()\fP Sets the value of the selected trip plan "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file cityselectwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CitySelectWindow::CitySelectWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file cityselectwindow\&.cpp\&.
.SS "CitySelectWindow::~CitySelectWindow ()"

.PP
Definition at line 11 of file cityselectwindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBCity\fP > & CitySelectWindow::getLoadedCities ()"

.PP
\fBgetLoadedCities()\fP Returns a vector containing the currently loaded cities 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<City> 
.RE
.PP

.PP
Definition at line 31 of file cityselectwindow\&.cpp\&.
.SS "int CitySelectWindow::getPlanNumber ()"

.PP
\fBgetPlanNumber()\fP Returns the value of the selected trip plan 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 36 of file cityselectwindow\&.cpp\&.
.SS "void CitySelectWindow::moveToFoodSelectClicked ()\fC [signal]\fP"

.PP
moveToFoodSelectClicked Proceeds to the \fBFood\fP Select window 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 138 of file moc_cityselectwindow\&.cpp\&.
.SS "void CitySelectWindow::setCitySelection ()"

.PP
\fBsetCitySelection()\fP Sets the city selection of the \fBCitySelectWindow\fP 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 16 of file cityselectwindow\&.cpp\&.
.SS "void CitySelectWindow::setPlanNumber (int number)"

.PP
\fBsetPlanNumber()\fP Sets the value of the selected trip plan 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIint\fP number 
.RE
.PP

.PP
Definition at line 41 of file cityselectwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
