.TH "CompareCity" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareCity \- \fBCompareCity\fP struct A comparator for cities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <city\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBCity\fP const &c1, \fBCity\fP const &c2)"
.br
.RI "operator a comparator for cities "
.in -1c
.SH "Detailed Description"
.PP 
\fBCompareCity\fP struct A comparator for cities\&. 


.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBDate:\fP
.RS 4
October 2019 
.RE
.PP

.PP
Definition at line 160 of file city\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CompareCity::operator() (\fBCity\fP const & c1, \fBCity\fP const & c2)\fC [inline]\fP"

.PP
operator a comparator for cities 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBDate:\fP
.RS 4
October 2019 
.RE
.PP

.PP
Definition at line 168 of file city\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
