.TH "C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/dbinit.h" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/dbinit.h
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
