.TH "FoodSelectWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoodSelectWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <foodselectwindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmoveToCitySelectClicked\fP ()"
.br
.RI "\fBmoveToCitySelectClicked()\fP Proceeds to the city select window "
.ti -1c
.RI "void \fBmoveToResultsClicked\fP ()"
.br
.RI "\fBmoveToResultsClicked()\fP Proceeds to the city results window "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoodSelectWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~FoodSelectWindow\fP ()"
.br
.ti -1c
.RI "void \fBsetFoodSelection\fP (std::vector< \fBCity\fP > &loadedCities)"
.br
.RI "\fBsetFoodSelection(std::vector<City>& loadedCities)\fP Sets the food selection of the \fBCitySelectWindow\fP "
.ti -1c
.RI "void \fBloadFoodQuantities\fP ()"
.br
.RI "\fBloadFoodQuantities()\fP Loads the quantities of food on the \fBCitySelectWindow\fP "
.ti -1c
.RI "std::vector< \fBCity\fP > & \fBgetLoadedCities\fP ()"
.br
.RI "\fBgetLoadedCities()\fP Returns a vector containing the currently loaded cities "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file foodselectwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FoodSelectWindow::FoodSelectWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file foodselectwindow\&.cpp\&.
.SS "FoodSelectWindow::~FoodSelectWindow ()"

.PP
Definition at line 11 of file foodselectwindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBCity\fP > & FoodSelectWindow::getLoadedCities ()"

.PP
\fBgetLoadedCities()\fP Returns a vector containing the currently loaded cities 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<City> 
.RE
.PP

.PP
Definition at line 88 of file foodselectwindow\&.cpp\&.
.SS "void FoodSelectWindow::loadFoodQuantities ()"

.PP
\fBloadFoodQuantities()\fP Loads the quantities of food on the \fBCitySelectWindow\fP 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 69 of file foodselectwindow\&.cpp\&.
.SS "void FoodSelectWindow::moveToCitySelectClicked ()\fC [signal]\fP"

.PP
\fBmoveToCitySelectClicked()\fP Proceeds to the city select window 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 154 of file moc_foodselectwindow\&.cpp\&.
.SS "void FoodSelectWindow::moveToResultsClicked ()\fC [signal]\fP"

.PP
\fBmoveToResultsClicked()\fP Proceeds to the city results window 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP

.PP
Definition at line 160 of file moc_foodselectwindow\&.cpp\&.
.SS "void FoodSelectWindow::setFoodSelection (std::vector< \fBCity\fP > & loadedCities)"

.PP
\fBsetFoodSelection(std::vector<City>& loadedCities)\fP Sets the food selection of the \fBCitySelectWindow\fP 
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvector<city>&\fP loadedCities 
.RE
.PP

.PP
Definition at line 16 of file foodselectwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
