.TH "LoginWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoginWindow \- \fBLoginWindow\fP This class allows the user to input a username and password, and verifies if their login information is valid If the login is valid, it opens the Edit Window If the login is invalid, the user is given an 'Invalid Username or Password' message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loginwindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmoveToEditClicked\fP ()"
.br
.RI "on_pushButton_BackButton_clicked() Redirects the window to the edit window of the program "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~LoginWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLoginWindow\fP This class allows the user to input a username and password, and verifies if their login information is valid If the login is valid, it opens the Edit Window If the login is invalid, the user is given an 'Invalid Username or Password' message\&. 
.PP
Definition at line 22 of file loginwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoginWindow::LoginWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file loginwindow\&.cpp\&.
.SS "LoginWindow::~LoginWindow ()"

.PP
Definition at line 11 of file loginwindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void LoginWindow::moveToEditClicked ()\fC [signal]\fP"

.PP
on_pushButton_BackButton_clicked() Redirects the window to the edit window of the program 
.PP
Definition at line 138 of file moc_loginwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
