.TH "C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/debug/qrc_europe.cpp" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/debug/qrc_europe.cpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_RCC_PREPEND_NAMESPACE\fP(name)   name"
.br
.ti -1c
.RI "#define \fBQT_RCC_MANGLE_NAMESPACE\fP(name)   name"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "int \fBQT_RCC_MANGLE_NAMESPACE\fP() \fBqInitResources_europe\fP ()"
.br
.ti -1c
.RI "int \fBQT_RCC_MANGLE_NAMESPACE\fP() \fBqCleanupResources_europe\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_RCC_MANGLE_NAMESPACE(name)   name"

.PP
Definition at line 55375 of file qrc_europe\&.cpp\&.
.SS "#define QT_RCC_PREPEND_NAMESPACE(name)   name"

.PP
Definition at line 55374 of file qrc_europe\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int \fBQT_RCC_MANGLE_NAMESPACE\fP() qCleanupResources_europe ()"

.PP
Definition at line 55399 of file qrc_europe\&.cpp\&.
.SS "int \fBQT_RCC_MANGLE_NAMESPACE\fP() qInitResources_europe ()"

.PP
Definition at line 55390 of file qrc_europe\&.cpp\&.
.SS "bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SS "bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
