.TH "qt_meta_stringdata_TripWindow_t" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_TripWindow_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [10]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [188]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file moc_tripwindow\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_TripWindow_t::data[10]"

.PP
Definition at line 25 of file moc_tripwindow\&.cpp\&.
.SS "char qt_meta_stringdata_TripWindow_t::stringdata0[188]"

.PP
Definition at line 26 of file moc_tripwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
