.TH "Ui" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- Header file for the \fBCitySelectWindow\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCitySelectWindow\fP"
.br
.ti -1c
.RI "class \fBEditWindow\fP"
.br
.ti -1c
.RI "class \fBFoodSelectWindow\fP"
.br
.ti -1c
.RI "class \fBLoginWindow\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.ti -1c
.RI "class \fBResultsWindow\fP"
.br
.ti -1c
.RI "class \fBTripWindow\fP"
.br
.ti -1c
.RI "class \fBViewWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBCitySelectWindow\fP\&. 

Header file for the \fBViewWindow\fP\&.
.PP
Header file for the \fBResultsWindow\fP\&.
.PP
Header file for the \fBMainWindow\fP\&.
.PP
This is the \fBLoginWindow\fP class used to verify a login attempt made by a user\&.
.PP
Header file for the \fBFoodSelectWindow\fP\&.
.PP
Header file for the \fBEditWindow\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Aaron Geesink 
.RE
.PP
\fBDate:\fP
.RS 4
October 2019
.RE
.PP
\fBAuthor:\fP
.RS 4
Garrett Geesink 
.RE
.PP
\fBDate:\fP
.RS 4
October 2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
