.TH "Ui::CitySelectWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::CitySelectWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_cityselectwindow\&.h>\fP
.PP
Inherits \fBUi_CitySelectWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 59 of file ui_cityselectwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
