.TH "Ui::EditWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::EditWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_editwindow\&.h>\fP
.PP
Inherits \fBUi_EditWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 164 of file ui_editwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
