.TH "Ui::ResultsWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ResultsWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_resultswindow\&.h>\fP
.PP
Inherits \fBUi_ResultsWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 64 of file ui_resultswindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
