.TH "Ui::TripWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::TripWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_tripwindow\&.h>\fP
.PP
Inherits \fBUi_TripWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 72 of file ui_tripwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
