.TH "Ui::ViewWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ViewWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_viewwindow\&.h>\fP
.PP
Inherits \fBUi_ViewWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 63 of file ui_viewwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
