.TH "C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/viewwindow.h" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/chatm/Desktop/CS1D-European-Vacation-Project/European-Vacation-Program/viewwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QtSql>\fP
.br
\fC#include <QtDebug>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include 'database\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBViewWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "Header file for the \fBCitySelectWindow\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
