.TH "ViewWindow" 3 "Sun Oct 20 2019" "Version 1.0" "European Vacation Planner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <viewwindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~ViewWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file viewwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ViewWindow::ViewWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file viewwindow\&.cpp\&.
.SS "ViewWindow::~ViewWindow ()"

.PP
Definition at line 11 of file viewwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for European Vacation Planner from the source code\&.
